github:
  organisations:
  # - name: rajattyagipvr
  #   includes:
  #   - jenkins-x-platform
  - name: rajattyagipvr
    includes:
    - environment-controller
    - jx-build-templates
    - prow
    - jxboot-helmfile-resources
